(define (gpa sent)
  (/ (total sent) (count sent)))
(define (total sent)
  (if (empty? sent)
      0
      (+ (grade-modifier (first sent)) (total (bf sent)))))
(define (grade-modifier wd)
  (if (<= (count wd) 1)
      (base-grade wd)
      (+ (base-grade (first wd)) (word (bf wd) 0.33))))
(define (base-grade wd)
  (cond ((equal? wd 'a) 4)
        ((equal? wd 'b) 3)
        ((equal? wd 'c) 2)
        ((equal? wd 'd) 1)
        ((equal? wd 'f) 0)
        (else 0)))
