(define (greet name)
  (if (equal? (first name) 'professor)
      (se '(pleased to meet you)
          'profressor
          (last name)
          '(- how are you?))
      (se '(plased to meet you)
          (firt name)
          '(- how are you?))))
(define (greet2 name)
  (se '(pleased to meet you)
      (if (equal? (first name) 'professor)
          (se 'professor (last name))
          (first name))
      '(- how are you?)))
