(define (valid-date? month date year)
  (cond ((= 0 (* month date year)) #f)
    	((member? month '(4 6 9 11)) (<= date 30))
	((and (= 2 month) (leap-year? year)) (<= date 29))
	((= 2 month) (<= date 28))
	(else (<= date 31))))
(define (leap-year? year)
  (cond ((divided? year 100) (divided? year 400))
	(else (divided? year 4))))
(define (divided? dividend divisor)
  (= 0 (remainder dividend divisor)))
