(define (tip x)
    (ceiling (* x (/ 15 100))))(define (tip x)
            (ceiling (* x (/ 15 100))))(define (tip x)
                    (ceiling (* x (/ 15 100))))(define (tip x)
                            (ceiling (* x (/ 15 100))))(define (tip x)
                                    (ceiling (* x (/ 15 100))))(define (tip x)
                                            (ceiling (* x (/ 15 100))))(define (tip x)
                                                    (ceiling (* x (/ 15 100))))(define (tip x)
                                                            (ceiling (* x (/ 15 100))))(define (tip x)
                                                                    (ceiling (* x (/ 15 100))))
