(define (every-nth num sent)
  (every-nth-helper num num sent))
(define (every-nth-helper con num sent)
  (if (empty? sent)
      '()
      (if (= num 1)
          (se (first sent) (every-nth-helper con con (bf sent)))
          (every-nth-helper con (- num 1) (bf sent)))))
