(define (expand sent)
  (if (< (count sent) 2)
      '()
      (if (number? (first sent))
          (se (expand-helper (first sent) (first (bf sent))) 
              (expand (bf sent)))
          (se (first sent) (expand (bf sent))))))
(define (expand-helper num wd)
  (if (= num 0)
      '()
      (se wd (expand-helper (- num 1) wd))))
