(define (safe-pigl sent)
  (if (empty? sent)
      '()
      (if (have-vowel? (first sent))
          (se (pigl (first sent)) (safe-pigl (bf sent)))
          (safe-pigl (bf sent)))))
(define (have-vowel? wd)
  (not (empty? (keep vowel? wd))))
(define (vowel? letter)
  (member? letter 'aeiou))
(define (pigl wd)
  (if (empty? wd)
      ""
      (if (vowel? (first wd))
          (word wd 'ay)
          (pigl (bf wd)))))
