; (mergesort '(i wanna be your man))
(define (mergesort sent)
  (if (<= (count sent) 1)
      sent
      (merge (mergesort (one-half sent))
             (mergesort (other-half sent)))))
(define (merge sent1 sent2)
  (cond ((empty? sent1) sent2)
        ((empty? sent2) sent1)
        ((and (empty? sent1) (empty? sent2)) '())
        ((before? (first sent1) (first sent2)) 
         (se (first sent1) (merge (bf sent1) sent2)))
        (else (se (first sent2) (merge sent1 (bf sent2))))))
(define (one-half sent)
  (if (<= (count sent) 1)
      sent
      (se (first sent) (one-half (bf (bf sent))))))
(define (other-half sent)
  (if (<= (count sent) 1)
      '()
      (se (first (bf sent)) (other-half (bf (bf sent))))))
