; (phone-spell 26) -> (am an ao bm bn bo cm cn co)
(define (phone-spell wd)
  (if (empty? wd)
      (se "")
      (se (combination (num-to-word (first wd))
                       (phone-spell (bf wd))))))
; (combination 'abc 'def) -> (ad ae af bd be bf cd ce cf)
(define (combination left right)
  (if (empty? left)
      '()
      (se (distribution (first left) right) 
          (combination (bf left) right))))
; (distribution 'a 'bcd) -> (ab ac ad)
(define (distribution letter wd)
  (if (empty? wd)
      '()
      (se (word letter (first wd)) (distribution letter (bf wd)))))
(define (num-to-word num)
  (cond ((= num 2) 'abc)
        ((= num 3) 'def)
        ((= num 4) 'ghi)
        ((= num 5) 'jkl)
        ((= num 6) 'mno)
        ((= num 7) 'pqr)
        ((= num 8) 'stu)
        ((= num 9) 'vwx)))
