; (sort '(i wanna be your man)) -> (be i man wanna your)
(define (sort sent)
  (if (empty? sent)
      '()
      (se (earliest-word sent) 
          (sort (remove-once (earliest-word sent) sent)))))
; (earliest-word '(i wanna be your man)) -> be
(define (earliest-word sent)
  (earliest-helper (first sent) (bf sent)))
; (earliest-helper 'i '(wanna be your man)) -> be
(define (earliest-helper so-far rest)
  (if (empty? rest)
      so-far
      (if (before? so-far (first rest))
          (earliest-helper so-far (bf rest))
          (earliest-helper (first rest) (bf rest)))))
; (remove-once 'be '(wanna be your man)) -> (wanna your man)
(define (remove-once wd sent) 
  (if (empty? sent)
      '()
      (if (equal? wd (first sent))
          (bf sent)
          (se (first sent) (remove-once wd (bf sent))))))
