; (substrings 'abc) -> (abc ab a bc b c)
(define (substrings wd)
  (if (empty? wd)
      '()
      (se (substrings-helper wd) 
          (substrings (bf wd)))))
; (substrings-helper 'abc) -> (abc ab a)
(define (substrings-helper wd)
  (if (empty? wd)
      '()
      (se wd (substrings-helper (bl wd)))))
