(define (gpa sent)
  (/ (accumulate + (every grade-modifier sent)) (count sent)))
(define (base-grade grade)
  (cond ((equal? grade 'A) 4)
	((equal? grade 'B) 3)
	((equal? grade 'C) 2)
	((equal? grade 'D) 1)
	((equal? grade 'F) 0)))
(define (grade-modifier grade)
  (+ (base-grade (first grade)) (cond ((member? '+ grade) 0.33)
		      ((member? '- grade) (- 0.33))
		      (else 0))))
